language: c
compiler:
  - gcc
before_install:
  - sudo apt-get update
  - sudo apt-get install -y protobuf-c-compiler lua5.2 liblua5.2-dev libopus-dev libvorbis-dev libssl-dev libev-dev
  - sed -i -e 1s/lua/lua5.2/ -e 1s/libprotobuf-c// -e 1s/$/\ -lprotobuf-c/ Makefile
script: make piepan
